# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 512e7848c5bc86abb1498f5d824be04ea51fb4b4fafb35b89d53e7ea542cde2278db22278186aabf73c25132e680750f85f2d89c5e57e7626c6e8d7827c36dfd

test:
  secret_key_base: a03411ced9459d0b334ced485c309e760b60df77a59a6a7f8a41ed14d1afa9824d016958fbd0e2ee022d9d9b63fc524e66da31f85c892dd414d5c6b8d6374228

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
